ci(pr-check): adding fail

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -12,5 +12,9 @@ jobs:
     name: Do Some CI Work
     runs-on: ubuntu-latest
     steps:
-      - run: sleep 1000
-      - run: echo "Working hard..."
+      - run: |
+          sleep 10
+          echo "Working hard..."
+          echo "..and still failing."
+          exit 1
+          
